spring:
  application:
    name: consumer
  profiles:
    active: uconsumer1
eureka:
  client:
    serviceUrl:
      defaultZone: http://eserver1:30000/eureka/,http://eserver2:30001/eureka/
  instance:
    prefer-ip-address: true #为true表示将自己的IP地址注册到Eureka Server，false表示将hostname注册到Eureka Server
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
---
spring:
  profiles: uconsumer1
server:
  port: 30004
---
spring:
  profiles: uconsumer2
server:
  port: 30005