spring:
  application:
    name: zuul
  profiles:
    active: zuul1
eureka:
  client:
    serviceUrl:
      defaultZone: http://eserver1:30000/eureka/,http://eserver2:30001/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      customer: 自定义元数据
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
---
spring:
  profiles: zuul1
server:
  port: 30012
---
spring:
  profiles: zuul2
server:
  port: 30013