version: '2'
services:
  eserver1:
    image: localhost:50000/wangxd/eureka-server:1.0-SNAPSHOT
    hostname: eserver1
    ports:
      - "30000:30000"
    environment:
      - spring.profiles.active=eserver1
    depends_on:
      - zipkin
  eserver2:
    image: localhost:50000/wangxd/eureka-server:1.0-SNAPSHOT
    hostname: eserver2
    environment:
      - spring.profiles.active=eserver2
    ports:
      - "30001:30001"
    depends_on:
      - eserver1
  service:
    image: localhost:50000/wangxd/u-service:1.0-SNAPSHOT
    hostname: service
    ports:
      - "30002:30002"
      - "30003:30003"
    depends_on:
      - eserver1
      - eserver2
  consumer:
    image: localhost:50000/wangxd/u-consumer:1.0-SNAPSHOT
    hostname: consumer
    ports:
      - "30004:30004"
      - "30005:30005"
    depends_on:
      - service
  zipkin:
    image: localhost:50000/wangxd/zipkin:1.0-SNAPSHOT
    hostname: zipkin
    ports:
      - "30006:30006"
      - "30007:30007"
#  dashboard:
#    image: localhost:50000/wangxd/hystrix-dashboard:1.0-SNAPSHOT
#    hostname: dashboard
#    ports:
#      - "30008:30008"
#      - "30009:30009"
#    depends_on:
#      - consumer
#  turbine:
#    image: localhost:50000/wangxd/hystrix-turbine:1.0-SNAPSHOT
#    hostname: turbine
#    ports:
#      - "30010:30010"
#      - "30011:30011"
#    depends_on:
#      - consumer
