spring:
  application:
    name: sidecar
  profiles:
    active: sidecar1
eureka:
  client:
    serviceUrl:
      defaultZone: http://eserver1:30000/eureka/,http://eserver2:30001/eureka/
  instance:
    prefer-ip-address: true
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
sidecar:
  port: 30016
  health-uri: http://localhost:30016/health
management:
  security:
    enabled: false
---
spring:
  profiles: sidecar1
server:
  port: 30014
---
spring:
  profiles: sidecar2
server:
  port: 30015