spring:
  application:
    name: turbine
  profiles:
    active: turbine1
eureka:
  client:
    serviceUrl:
      defaultZone: http://eserver1:30000/eureka/,http://eserver2:30001/eureka/
  instance:
    prefer-ip-address: true #为true表示将自己的IP地址注册到Eureka Server，false表示将hostname注册到Eureka Server
logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
turbine:
  app-config: service,consumer
  cluster-name-expression: "'default'"
---
spring:
  profiles: turbine1
server:
  port: 30010
---
spring:
  profiles: turbin2
server:
  port: 30011